[phases.setup]
nixPkgs = ['php', 'php81Packages.composer', 'nodejs_18', 'mysql', 'imagemagick']

[phases.build]
cmds = [
  "composer install",
  "npm install",
  "npm run build",
  "chmod -R 777 storage bootstrap/cache",  # permisos antes de optimizar
  "php artisan migrate --force",
  "php artisan optimize",
  "php artisan storage:link"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
